name: lotka
channels:
    - conda
    - conda-forge
    - defaults
dependencies:
    - python=3.12.3
    - pip
    - numba
    - cuda-nvcc
    - cuda-nvrtc
    - cuda-version>=12.0
    - pip:
          - numpy==1.26.4
          - matplotlib==3.8.4
          - argparse==1.4.0
          - networkx==3.3
          - sqlalchemy==2.0.34
          - asyncio==3.4.3
          - psycopg2==2.9.9
